# Generated by Django 2.0.3 on 2018-03-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_new_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_bio',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='A short bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_goals',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Your goals'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Your name'),
        ),
    ]
