# Generated by Django 2.0.3 on 2018-04-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180329_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_bio',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='A short bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_goals',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Your current goals'),
        ),
    ]
