# Generated by Django 2.0.3 on 2018-04-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180402_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_bio',
            field=models.TextField(blank=True, null=True, verbose_name='A short bio'),
        ),
    ]
