# Generated by Django 2.0.3 on 2018-04-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180402_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_lists',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_account',
            field=models.BooleanField(default=False),
        ),
    ]
