# Generated by Django 2.0.4 on 2018-04-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180412_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/user_default.png', null=True, upload_to='media/profile_pics'),
        ),
    ]
