# Generated by Django 2.0.3 on 2018-04-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifftasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ifflist',
            old_name='user_id',
            new_name='user',
        ),
    ]
