# Generated by Django 2.0.3 on 2018-04-05 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifftasks', '0002_auto_20180403_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='ifflist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='ifftasks.IffList'),
        ),
    ]
