# Generated by Django 2.0.3 on 2018-04-06 02:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ifftasks', '0004_auto_20180405_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifflist',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
