# Generated by Django 2.0.3 on 2018-04-06 02:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ifftasks', '0005_ifflist_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
