# Generated by Django 2.0.3 on 2018-04-06 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifftasks', '0006_todoitem_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifflist',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='uuid',
        ),
    ]
