# Generated by Django 2.0.4 on 2018-04-10 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifftasks', '0007_auto_20180406_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='ifflist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifftasks.IffList'),
        ),
    ]
