# Generated by Django 2.0.4 on 2018-04-10 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifftasks', '0010_auto_20180410_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifflist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
