# Generated by Django 2.0.4 on 2018-04-12 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ifftasks', '0011_auto_20180410_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifflist',
            name='completed_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
